### ISSUE TITLE
Duplicate headers should be treated as error conditions, not accumulate daa

### ISSUE THREAD

**Issue by chthonicionic** [orangemug/csv-nested#1]
The current logic if a key already exists in the output data structure is to concatenate the two items together:

```
        if(out[header] !== undefined && out[header] !== "") {
          out[header] += item;
        } else {
          out[header] = item;
        }
```

Two cells having the same header hierachy should be treated as malformed input instead.

```
        if(out[header] !== undefined) {
          //suggest we throw an error here instead alerting the user that header is duplicated
          //NB empty string test removed
        } else {
          out[header] = item;
        }
```

**Comment by orangemug** [comment]
@chthonicionic `v0.2.0` has been released

https://github.com/orangemug/csv-nested/compare/v0.1.0...v0.2.0

Please give it a look over/test check your happy.
